// cmd/dashboard.go
package cmd

import (
	"PRism/config"
	"PRism/dashboard"
	"PRism/github"
	"PRism/llm"
	"bufio"
	"context"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var dashboardCmd = &cobra.Command{
	Use:   "dashboard",
	Short: "Generate Grafana and Amplitude dashboard of PR metrics and data",
	Long: `Generates a Grafana and Amplitude dashboard of PR metrics and data.
You can view visualizations of PR data, trends, and other insights.`,
	Run: func(cmd *cobra.Command, args []string) {
		runDashboard()
	},
}

func init() {
	rootCmd.AddCommand(dashboardCmd)
}

func runDashboard() {
	log.Println("Starting dashboard generation...")

	cfg := config.LoadConfig()
	log.Println("Config loaded successfully")

	// Initialize GitHub client
	ctx := context.Background()
	githubClient := github.InitializeGithubClient(cfg, ctx)
	log.Println("GitHub client initialized")

	// Fetch PR details including diff
	log.Println("Fetching PR details...")
	prDetails, err := github.FetchPRDetails(githubClient, cfg)
	if err != nil {
		log.Fatalf("Error fetching PR details: %v", err)
	}
	log.Printf("Successfully fetched PR details for PR #%d", prDetails["number"])

	// Read PRD content if provided
	prdContent := ""
	if cfg.PRDFilePath != "" {
		log.Printf("Attempting to read PRD file from: %s", cfg.PRDFilePath)
		content, err := os.ReadFile(cfg.PRDFilePath)
		if err != nil {
			log.Printf("Warning: Could not read PRD file: %v", err)
		} else {
			prdContent = string(content)
			log.Println("Successfully read PRD content")
		}
	}

	// Prepare prompt for Claude
	log.Println("Building dashboard prompt...")
	prompt := llm.BuildDashboardPrompt(prDetails, prdContent)
	log.Println("Dashboard prompt built successfully")

	// Call Claude API
	log.Println("Calling Claude API for dashboard suggestions...")
	suggestions, err, _, summary := llm.CallClaudeAPIForDashboards(prompt, cfg)
	log.Printf("Received summary from Claude: %s", summary)
	if err != nil {
		log.Fatalf("Error calling Claude API: %v", err)
	}

	if suggestions == nil || len(*suggestions) == 0 {
		log.Println("No dashboard suggestions were generated by Claude")
	} else {
		log.Printf("Successfully received %d dashboard suggestions from Claude", len(*suggestions))

		// Log the suggestions
		for i, suggestion := range *suggestions {
			log.Printf("Dashboard suggestion %d: %s (%s) - Priority: %s", i+1, suggestion.Name, suggestion.Type, suggestion.Priority)
		}

		// Create PR comments if suggestions exist
		log.Println("Creating PR comments with dashboard suggestions...")
		err := github.CreateDashboardPRComments(*suggestions, prDetails, cfg, summary)
		if err != nil {
			log.Fatalf("Error creating Dashboard PR comments: %v", err)
		}
		log.Println("Successfully created PR comments")

		// Ask user if they want to create the dashboards now
		reader := bufio.NewReader(os.Stdin)
		fmt.Println("\nDo you want to create these dashboards now? (y/n)")
		input, _ := reader.ReadString('\n')
		input = strings.TrimSpace(strings.ToLower(input))

		if input == "y" || input == "yes" {
			log.Println("Starting dashboard creation process...")
			for _, suggestion := range *suggestions {
				if suggestion.Type == "grafana" {
					log.Printf("Creating Grafana dashboard: %s", suggestion.Name)
					err := dashboard.CreateGrafanaDashboard(suggestion, cfg)
					if err != nil {
						log.Printf("Error creating Grafana dashboard '%s': %v", suggestion.Name, err)
					} else {
						log.Printf("Successfully created Grafana dashboard: %s", suggestion.Name)
					}
				} else if suggestion.Type == "amplitude" {
					log.Printf("Creating Amplitude dashboard: %s", suggestion.Name)
					err := dashboard.CreateAmplitudeDashboard(suggestion, cfg)
					if err != nil {
						log.Printf("Error creating Amplitude dashboard '%s': %v", suggestion.Name, err)
					} else {
						log.Printf("Successfully created Amplitude dashboard: %s", suggestion.Name)
					}
				}
			}
			log.Println("Dashboard creation process completed")
		} else {
			log.Println("Dashboard creation skipped. You can create them later from the PR comments.")
		}
	}
	log.Println("Dashboard generation process completed")
}
