groups:
- name: metric
  rules:
  - alert: DatadogAPILatency
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="tracepr", target_service="datadog"}[5m])) by (le)) > 2
    for: 5m
    labels:
      severity: p1
      type: metric
    annotations:
      summary: "DatadogAPILatency"
      description: "Datadog API requests are taking longer than expected, which may impact alert creation functionality."
      runbook_url: "https://github.com/organization/tracepr/wiki/datadog-integration-issues"
