name: PRism Comment Trigger

on:
  issue_comment:
    types: [created]
permissions:
  pull-requests: write
  contents: read
  issues: read 

jobs:
  analyze:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Build PRism
        run: go build -o prism
        
      - name: Get PR Number
        id: get_pr_number
        run: |
          PR_NUMBER=$(echo ${{ github.event.issue.number }})
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          
      - name: Run PRism Check
        if: github.event.comment.body == 'prism check'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ steps.get_pr_number.outputs.pr_number }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          GRAFANA_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GRAFANA_SERVICE_ACCOUNT_TOKEN }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
        run: ./prism check
        
      - name: Run PRism Dashboard
        if : github.event.comment.body == 'prism dashboard'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ steps.get_pr_number.outputs.pr_number }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          GRAFANA_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GRAFANA_SERVICE_ACCOUNT_TOKEN }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
        run: ./prism dashboard
        
      - name: Run PRism Alerts
        if: github.event.comment.body == 'prism alerts'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ steps.get_pr_number.outputs.pr_number }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          GRAFANA_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GRAFANA_SERVICE_ACCOUNT_TOKEN }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
        run: ./prism alerts 